// <auto-generated />
namespace Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removedatetoolkit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedatetoolkit));
        
        string IMigrationMetadata.Id
        {
            get { return "201508190418334_remove-date-toolkit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
